### PR TITLE
Vet clinic database: database performance audit

### PR DESCRIPTION
**Pull request by habasm**
### Screenshot for the process
- These below screenshot are explained queries 

- The following queries snapshot are after optimized queries to some levels
1indexed
2indexed
3indexed

### CODE REVIEW

**Review by alexander16108 — CHANGES_REQUESTED** [review]
Hi @habasm @kal2944 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] the execution time for the query `EXPLAIN ANALYZE SELECT * FROM owners where email = 'owner_18327@mail.com'`, `EXPLAIN ANALYZE SELECT COUNT(*) FROM visits where animal_id = 4;` `EXPLAIN ANALYZE SELECT * FROM visits where vet_id = 2` is not significantly lower than 1 sec (1000ms) as you can see in the screenshot of your PR. 😄 I suggest running the populate database query a few times more as described in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_performance_audit.md#:~:text=4%20Depening%20on,bigger%20than%201000ms.) and take a screen of a good result with execution time less than 1 sec (1000ms)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by habasm** [comment]
### @alexander16108  Thanks for your comment, Now we rerun the step-3 and actually recording a new screenshots and available on the pull request descriptions.  and your assumptions and requirements are a bit different

**Comment by habasm** [comment]
@alexander16108  actually indexed attributes can minimize the execution time, it should be considered also. Thanks!

**Comment by habasm** [comment]
@alexander16108 this is the requirement
 Depening on your machine speed, it might be enough or not. Check that by running explain analyze SELECT COUNT(*) FROM visits where animal_id = 4: - If you get Execution time: X ms and X >= 1000: that should be enough, you can continue to the project requirements. - If you get Execution time: X ms and X < 1000: please go back to point 3. and repeat until you get a value bigger than 1000ms.
 
 And you said less than...

**Review by franclobo — APPROVED** [review]
Hi @habasm and @kal2944, 

# STATUS: APPROVED 😃 

git-merge

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Correct Git flow ✔️ 
- Descriptive PR ✔️ 
- Good execution time 👍🏽 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
